#!/usr/bin/env python3
"""Assemble the chem-suite skill from chem-tools, cdx-tools and tools/suite/.

    python tools/assemble_suite.py

chem-suite is generated: never edit files in chem-suite/ directly. Change the tool code in
chem-tools/ or cdx-tools/ (the single source of truth) or the suite-specific files in
tools/suite/, then rerun this script (tools/build.py runs it automatically).
"""

import json
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CHEM, CDX, SUITE_SRC = ROOT / "chem-tools", ROOT / "cdx-tools", ROOT / "tools" / "suite"
OUT = ROOT / "chem-suite"
NOTICE = "GENERATED by tools/assemble_suite.py - edit chem-tools/, cdx-tools/ or tools/suite/ instead.\n"

SUITE_SETTINGS = '''COMPANION = None                    # chem-suite contains both toolsets
COMPANION_LAUNCHER = ""
COMPANION_PROBE = ""
COMPANION_ROLE = ""
ENDPOINTS = {"pubchem": "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/2244/property/Title/TXT",
             "chembl": "https://www.ebi.ac.uk/chembl/api/data/status.json"}
CHECK_CHEMDRAW = True
'''


def version_of(skill: Path) -> str:
    m = re.search(r'^\s*version:\s*"?([\d.]+)', (skill / "SKILL.md").read_text(), re.MULTILINE)
    return m.group(1)


def suite_version() -> str:
    """Suite version tracks its sources: the highest of the two skills' versions."""
    return max(version_of(CHEM), version_of(CDX), key=lambda v: tuple(map(int, v.split("."))))


def assemble() -> str:
    if OUT.exists():
        shutil.rmtree(OUT)
    (OUT / "scripts").mkdir(parents=True)
    (OUT / "references").mkdir()
    (OUT / ".claude-plugin").mkdir()
    s = OUT / "scripts"

    # Tool code, unchanged from its home skill
    for name in ("chem_tools.py", "pubchem.py", "diagnostics.py", "reagents.json"):
        shutil.copy2(CHEM / "scripts" / name, s / name)
    for name in ("cdx_tools.py", "cdxml_writer.py"):
        shutil.copy2(CDX / "scripts" / name, s / name)
    shutil.copy2(CHEM / "scripts" / "tool_schemas.py", s / "chem_schemas.py")
    shutil.copy2(CDX / "scripts" / "tool_schemas.py", s / "cdx_schemas.py")
    for f in ("pubchem.py", "diagnostics.py", "reagents.json"):
        if (CHEM / "scripts" / f).read_bytes() != (CDX / "scripts" / f).read_bytes():
            raise SystemExit(f"{f} differs between chem-tools and cdx-tools; make them identical first.")

    # Launcher, CLI and system check from chem-tools, with suite names/settings
    launcher = (CHEM / "scripts" / "chem").read_text().replace('NAME="chem-tools"', 'NAME="chem-suite"')
    launcher = launcher.replace("# chem-tools launcher:", "# chem-suite launcher:")
    (s / "chem").write_text(launcher)
    (s / "chem").chmod(0o755)
    cli = (CHEM / "scripts" / "chem.py").read_text()
    cli = cli.replace("for the chem-tools skill", "for the chem-suite skill")
    cli = cli.replace("(Python, RDKit, PubChem/ChEMBL, cdx-tools)", "(Python, RDKit, PubChem/ChEMBL, ChemDraw)")
    (s / "chem.py").write_text(cli)
    (s / "chem.py").chmod(0o755)
    check = (CHEM / "scripts" / "check_env.py").read_text()
    block = re.search(r"# ---- per-skill settings\n(.*?)# ----\n", check, re.DOTALL)
    check = check.replace(block.group(1), SUITE_SETTINGS)
    (s / "check_env.py").write_text(check)

    # Suite-specific files
    shutil.copy2(SUITE_SRC / "tool_schemas.py", s / "tool_schemas.py")
    shutil.copy2(SUITE_SRC / "mcp_server.py", s / "mcp_server.py")
    version = suite_version()
    (OUT / "SKILL.md").write_text((SUITE_SRC / "SKILL.md").read_text().replace("__VERSION__", version))

    # References: one tool reference covering both toolsets
    shutil.copy2(CHEM / "references" / "smarts.md", OUT / "references" / "smarts.md")
    shutil.copy2(SUITE_SRC / "mcp-setup.md", OUT / "references" / "mcp-setup.md")
    chem_ref = (CHEM / "references" / "tools.md").read_text()
    cdx_ref = (CDX / "references" / "tools.md").read_text()
    chem_ref = chem_ref.replace("# Tool reference", "# Tool reference\n\n## Part 1: information tools", 1)
    chem_ref = re.sub(r"`scripts/chem schema <tool>`", "`bash scripts/chem schema <tool>`", chem_ref)
    cdx_ref = cdx_ref.split("\n", 1)[1]  # drop its title
    cdx_ref = cdx_ref.replace("`scripts/cdx schema <tool>`", "`bash scripts/chem schema <tool>`")
    (OUT / "references" / "tools.md").write_text(chem_ref.rstrip() + "\n\n---\n\n# Part 2: ChemDraw tools\n" + cdx_ref)

    shutil.copy2(ROOT / "LICENSE", OUT / "LICENSE")
    manifest = json.loads((CHEM / ".claude-plugin" / "plugin.json").read_text())
    manifest.update(
        name="chem-suite", version=version,
        description="All-in-one chemistry toolkit: compound information, hazards, properties and searches "
                    "(PubChem, ChEMBL, RDKit) plus native ChemDraw .cdxml figures and reaction schemes.",
        keywords=sorted(set(manifest["keywords"]) | {"chemdraw", "cdxml", "reaction scheme"}))
    manifest.pop("dependencies", None)
    (OUT / ".claude-plugin" / "plugin.json").write_text(json.dumps(manifest, indent=2) + "\n")
    (OUT / "GENERATED.txt").write_text(NOTICE)
    return version


if __name__ == "__main__":
    v = assemble()
    print(f"assembled chem-suite {v} in {OUT.relative_to(ROOT)}/")
